// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi_Day01.Model;

#nullable disable

namespace WebApi_Day01.Migrations
{
    [DbContext(typeof(ITIcontext))]
    [Migration("20250601122129_insert_data")]
    partial class insert_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi_Day01.Model.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Crs_desc")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Crs_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crs_desc = "Intro to C#",
                            Crs_name = "C# Basics",
                            Duration = 30
                        },
                        new
                        {
                            Id = 2,
                            Crs_desc = "Build Web APIs",
                            Crs_name = "ASP.NET Core",
                            Duration = 40
                        },
                        new
                        {
                            Id = 3,
                            Crs_desc = "Data access",
                            Crs_name = "EF Core",
                            Duration = 25
                        },
                        new
                        {
                            Id = 4,
                            Crs_desc = "Query databases",
                            Crs_name = "SQL Server",
                            Duration = 35
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
