// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WinFormsApp1.Models;

public partial class Student
{
    [Key]
    public int StudentId { get; set; }

    [StringLength(100)]
    public string FName { get; set; }

    [StringLength(50)]
    public string LName { get; set; }

    [StringLength(100)]
    public string Addresss { get; set; }

    public int? Age { get; set; }

    public int? Dept_Id { get; set; }

    public int? St_Super { get; set; }

    [InverseProperty("St_SuperNavigation")]
    public virtual ICollection<Student> InverseSt_SuperNavigation { get; set; } = new List<Student>();

    [ForeignKey("St_Super")]
    [InverseProperty("InverseSt_SuperNavigation")]
    public virtual Student St_SuperNavigation { get; set; }
}