// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApiDay02.Models;

[Table("Students")]
public partial class Student1
{
    [Key]
    public int StudentId { get; set; }

    [StringLength(100)]
    public string FName { get; set; }

    [StringLength(50)]
    public string LName { get; set; }

    [StringLength(100)]
    public string Addresss { get; set; }

    public int? Age { get; set; }

    public int? Dept_Id { get; set; }

    public int? St_Super { get; set; }

    [InverseProperty("St_SuperNavigation")]
    public virtual ICollection<Student1> InverseSt_SuperNavigation { get; set; } = new List<Student1>();

    [ForeignKey("St_Super")]
    [InverseProperty("InverseSt_SuperNavigation")]
    public virtual Student1 St_SuperNavigation { get; set; }
}